const states = [
  { stateFips: 1, stateLong: "ALABAMA", stateAbbr: "AL" },
  { stateFips: 2, stateLong: "ALASKA", stateAbbr: "AK" },
  { stateFips: 4, stateLong: "ARIZONA", stateAbbr: "AZ" },
  { stateFips: 5, stateLong: "ARKANSAS", stateAbbr: "AR" },
  { stateFips: 6, stateLong: "CALIFORNIA", stateAbbr: "CA" },
  { stateFips: 8, stateLong: "COLORADO", stateAbbr: "CO" },
  { stateFips: 9, stateLong: "CONNECTICUT", stateAbbr: "CT" },
  { stateFips: 10, stateLong: "DELAWARE", stateAbbr: "DE" },
  { stateFips: 11, stateLong: "DISTRICT OF COLUMBIA", stateAbbr: "DC" },
  { stateFips: 12, stateLong: "FLORIDA", stateAbbr: "FL" },
  { stateFips: 13, stateLong: "GEORGIA", stateAbbr: "GA" },
  { stateFips: 15, stateLong: "HAWAII", stateAbbr: "HI" },
  { stateFips: 16, stateLong: "IDAHO", stateAbbr: "ID" },
  { stateFips: 17, stateLong: "ILLINOIS", stateAbbr: "IL" },
  { stateFips: 18, stateLong: "INDIANA", stateAbbr: "IN" },
  { stateFips: 19, stateLong: "IOWA", stateAbbr: "IA" },
  { stateFips: 20, stateLong: "KANSAS", stateAbbr: "KS" },
  { stateFips: 21, stateLong: "KENTUCKY", stateAbbr: "KY" },
  { stateFips: 22, stateLong: "LOUISIANA", stateAbbr: "LA" },
  { stateFips: 23, stateLong: "MAINE", stateAbbr: "ME" },
  { stateFips: 24, stateLong: "MARYLAND", stateAbbr: "MD" },
  { stateFips: 25, stateLong: "MASSACHUSETTS", stateAbbr: "MA" },
  { stateFips: 26, stateLong: "MICHIGAN", stateAbbr: "MI" },
  { stateFips: 27, stateLong: "MINNESOTA", stateAbbr: "MN" },
  { stateFips: 28, stateLong: "MISSISSIPPI", stateAbbr: "MS" },
  { stateFips: 29, stateLong: "MISSOURI", stateAbbr: "MO" },
  { stateFips: 30, stateLong: "MONTANA", stateAbbr: "MT" },
  { stateFips: 31, stateLong: "NEBRASKA", stateAbbr: "NE" },
  { stateFips: 32, stateLong: "NEVADA", stateAbbr: "NV" },
  { stateFips: 33, stateLong: "NEW HAMPSHIRE", stateAbbr: "NH" },
  { stateFips: 34, stateLong: "NEW JERSEY", stateAbbr: "NJ" },
  { stateFips: 35, stateLong: "NEW MEXICO", stateAbbr: "NM" },
  { stateFips: 36, stateLong: "NEW YORK", stateAbbr: "NY" },
  { stateFips: 37, stateLong: "NORTH CAROLINA", stateAbbr: "NC" },
  { stateFips: 38, stateLong: "NORTH DAKOTA", stateAbbr: "ND" },
  { stateFips: 39, stateLong: "OHIO", stateAbbr: "OH" },
  { stateFips: 40, stateLong: "OKLAHOMA", stateAbbr: "OK" },
  { stateFips: 41, stateLong: "OREGON", stateAbbr: "OR" },
  { stateFips: 42, stateLong: "PENNSYLVANIA", stateAbbr: "PA" },
  { stateFips: 44, stateLong: "RHODE ISLAND", stateAbbr: "RI" },
  { stateFips: 45, stateLong: "SOUTH CAROLINA", stateAbbr: "SC" },
  { stateFips: 46, stateLong: "SOUTH DAKOTA", stateAbbr: "SD" },
  { stateFips: 47, stateLong: "TENNESSEE", stateAbbr: "TN" },
  { stateFips: 48, stateLong: "TEXAS", stateAbbr: "TX" },
  { stateFips: 49, stateLong: "UTAH", stateAbbr: "UT" },
  { stateFips: 50, stateLong: "VERMONT", stateAbbr: "VT" },
  { stateFips: 51, stateLong: "VIRGINIA", stateAbbr: "VA" },
  { stateFips: 53, stateLong: "WASHINGTON", stateAbbr: "WA" },
  { stateFips: 54, stateLong: "WEST VIRGINIA", stateAbbr: "WV" },
  { stateFips: 55, stateLong: "WISCONSIN", stateAbbr: "WI" },
  { stateFips: 56, stateLong: "WYOMING", stateAbbr: "WY" },
];
module.exports.states = states;
